#!/bin/sh

## This file is useful for testing the actual velocity framework itself and 
## will eventually be removed!

export VELOCITY_DEBUG=1
export MONGO_URL=mongodb://localhost:27017/velocity
meteor
